### ISSUE TITLE
Do you want to transfer ownership into the Swagger2markup Organisation?

### ISSUE THREAD

**Issue by RobWin** [Swagger2Markup/swagger2markup-cli#2]

**Comment by mxl** [comment]
Yes. How can I do this? Can not you just clone it to Swagger2markup Organization?

**Comment by RobWin** [comment]
https://help.github.com/articles/transferring-a-repository

I add you to the team then.

**Comment by RobWin** [comment]
I created a team and invited you.

**Comment by mxl** [comment]
Thx. I joined team but to transfer the repository I need owner rights within Swagger2markup organization.  See https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

**Comment by RobWin** [comment]
Done. Can you try again?

**Comment by mxl** [comment]
I received notification but I'm still not an admin https://github.com/orgs/Swagger2Markup/people?query=role%3Aowner

**Comment by RobWin** [comment]
You are admin of the Team "CLI". As far as I understand you don't have to be an owner.

**Comment by RobWin** [comment]
If it still doesnt work, you could transfer the ownership to me and I transfer it to the Organisation.

**Comment by mxl** [comment]
It works only with whole organization ownership. I transferred the repository directly to you.

**Comment by RobWin** [comment]
Thx
